apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: airflow
stringData:
  RABBITMQ_DEFAULT_USER: airflow
  RABBITMQ_DEFAULT_PASS: airflow # TODO: change this password
  RABBITMQ_DEFAULT_VHOST: airflow