apiVersion: v1
kind: Secret
metadata:
  name: airflow
  namespace: airflow
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://postgres:postgres@postgres.airflow/postgres
  AIRFLOW__CORE__LOAD_EXAMPLES: "true"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "false"
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CELERY__BROKER_URL: amqp://airflow:airflow@rabbitmq.airflow:5672/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgres://postgres:postgres@postgres.airflow/postgres
