apiVersion: v1
kind: Secret
metadata:
  name: airflow
  namespace: airflow
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://postgres:postgres@postgres.airflow/postgres
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "false"
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CELERY__BROKER_URL: amqp://airflow:airflow@rabbitmq.airflow:5672/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgres://postgres:postgres@postgres.airflow/postgres
#  https://airflow.apache.org/docs/stable/configurations-ref.html#worker-autoscale
  AIRFLOW__CELERY__WORKER_AUTOSCALE: 8,4
  AIRFLOW__CELERY__FLOWER_BASIC_AUTH: flower:flower
  AIRFLOW__WEBSERVER__WORKERS: "1"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "true"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.contrib.auth.backends.password_auth
  AIRFLOW__WEBSERVER__SECRET_KEY: temporary_key
  AIRFLOW__SCHEDULER__MAX_THREADS: "1"