apiVersion: v1
kind: Secret
metadata:
  name: airflow
  namespace: airflow
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://postgres:postgres@postgres.airflow/postgres
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "false"
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  # https://airflow.apache.org/docs/stable/configurations-ref.html#fernet-key
  AIRFLOW__CORE__FERNET_KEY: "{FERNET_KEY}"
  AIRFLOW__CELERY__BROKER_URL: amqp://airflow:airflow@rabbitmq.airflow:5672/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgres://postgres:postgres@postgres.airflow/postgres
  # https://airflow.apache.org/docs/stable/configurations-ref.html#worker-autoscale
  AIRFLOW__CELERY__WORKER_AUTOSCALE: 8,4
  AIRFLOW__CELERY__FLOWER_BASIC_AUTH: flower:flower
  AIRFLOW__WEBSERVER__WORKERS: "4"
  # https://airflow.apache.org/docs/stable/configurations-ref.html#worker-class
  AIRFLOW__WEBSERVER__WORKER_CLASS: gevent
  # https://airflow.apache.org/docs/stable/configurations-ref.html#rbac
  AIRFLOW__WEBSERVER__RBAC: "true"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "true"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.contrib.auth.backends.password_auth
  # https://airflow.apache.org/docs/stable/configurations-ref.html#secret-key
  AIRFLOW__WEBSERVER__SECRET_KEY: temporary_key
  AIRFLOW__SCHEDULER__MAX_THREADS: "1"
  GIT_REPO: https://github.com/WatchDG/airflow-dags.git
