apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: scheduler
  serviceName: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: repo
          image: watchdg/repo
          imagePullPolicy: Always
          workingDir: /opt/airflow/dags
          command:
            - sh
            - -c
            - git clone $(GIT_REPO) . && watch -n 60 git pull
          env:
            - name: GIT_REPO
              valueFrom:
                secretKeyRef:
                  name: airflow
                  key: GIT_REPO
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
        - name: scheduler
          image: watchdg/airflow:1
          imagePullPolicy: Always
          args:
            - scheduler
          envFrom:
            - secretRef:
                name: airflow
          ports:
            - containerPort: 8125
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          emptyDir: {}