apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: worker
  serviceName: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: repo
          image: watchdg/repo
          imagePullPolicy: Always
          workingDir: /opt/airflow/dags
          command:
            - sh
            - -c
            - git clone $(GIT_REPO) . && watch -n 60 git pull
          env:
            - name: GIT_REPO
              valueFrom:
                secretKeyRef:
                  name: airflow
                  key: GIT_REPO
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
        - name: worker
          image: watchdg/airflow:1
          imagePullPolicy: Always
          args:
            - worker
          ports:
            - containerPort: 8793
          envFrom:
            - secretRef:
                name: airflow
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          emptyDir: {}