apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flowere
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: flowere
  serviceName: flowere
  template:
    metadata:
      labels:
        app: flowere
    spec:
      containers:
        - name: flowere
          image: watchdg/airflow:1
          imagePullPolicy: Always
          args:
            - flower
          ports:
            - containerPort: 5555
          envFrom:
            - secretRef:
                name: airflow